// GENERATED by scripts/gen-seed-data.ts — do not edit by hand.
// Source: data/seed-entries.csv, data/seed-wife-payments.csv
// Regenerate with: npm run db:seed:gen
import type { Kind, LedgerKind } from "@/db/schema";

export type SeedEntry = {
  seedKey: string;
  date: string;
  kind: Kind;
  base: string;
  tip: string;
  wifeAlong: boolean;
  tripNumber: string | null;
  orders: number | null;
  completedTime: string | null;
  orderNumber: string | null;
  deliveredDate: string | null;
  notes: string;
};

export type SeedLedgerRow = {
  seedKey: string;
  date: string;
  kind: LedgerKind;
  amount: string;
  notes: string;
};

export const SEED_ENTRIES: SeedEntry[] = [
  {
    "seedKey": "seed-entries#1",
    "date": "2026-09-06",
    "kind": "trip",
    "base": "62.75",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": null,
    "orders": null,
    "completedTime": null,
    "orderNumber": null,
    "deliveredDate": null,
    "notes": "Week of 8/31 total, no per-order breakdown"
  },
  {
    "seedKey": "seed-entries#2",
    "date": "2026-09-07",
    "kind": "trip",
    "base": "25.77",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "8612",
    "orders": 1,
    "completedTime": "5:02 PM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#3",
    "date": "2026-09-07",
    "kind": "trip",
    "base": "26.49",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "9875",
    "orders": 1,
    "completedTime": "6:36 PM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#4",
    "date": "2026-09-07",
    "kind": "trip",
    "base": "45.51",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "3748",
    "orders": 1,
    "completedTime": "8:37 PM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#5",
    "date": "2026-09-08",
    "kind": "trip",
    "base": "37.68",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "8596",
    "orders": 1,
    "completedTime": "8:08 PM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#6",
    "date": "2026-09-08",
    "kind": "incentive",
    "base": "4.00",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": null,
    "orders": null,
    "completedTime": null,
    "orderNumber": null,
    "deliveredDate": null,
    "notes": "Incentive"
  },
  {
    "seedKey": "seed-entries#7",
    "date": "2026-09-09",
    "kind": "trip",
    "base": "12.33",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "0185",
    "orders": 1,
    "completedTime": "9:49 AM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#8",
    "date": "2026-09-09",
    "kind": "trip",
    "base": "10.00",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "9915",
    "orders": 1,
    "completedTime": "1:09 PM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#9",
    "date": "2026-09-09",
    "kind": "trip",
    "base": "13.57",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "1118",
    "orders": 1,
    "completedTime": "1:48 PM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#10",
    "date": "2026-09-09",
    "kind": "trip",
    "base": "28.79",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "9304",
    "orders": 3,
    "completedTime": "5:17 PM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#11",
    "date": "2026-09-09",
    "kind": "trip",
    "base": "69.42",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "6458",
    "orders": 1,
    "completedTime": "9:16 PM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#12",
    "date": "2026-09-09",
    "kind": "trip",
    "base": "18.95",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "5743",
    "orders": 1,
    "completedTime": "10:24 PM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#13",
    "date": "2026-09-10",
    "kind": "trip",
    "base": "10.00",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "5797",
    "orders": 1,
    "completedTime": "10:48 AM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#14",
    "date": "2026-09-10",
    "kind": "trip",
    "base": "41.59",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "6281",
    "orders": 1,
    "completedTime": "1:57 PM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#15",
    "date": "2026-09-10",
    "kind": "trip",
    "base": "39.16",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "2399",
    "orders": 1,
    "completedTime": "8:42 PM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#16",
    "date": "2026-09-10",
    "kind": "tip",
    "base": "0.00",
    "tip": "8.85",
    "wifeAlong": false,
    "tripNumber": null,
    "orders": null,
    "completedTime": null,
    "orderNumber": "200015425067806",
    "deliveredDate": "2026-09-09",
    "notes": ""
  },
  {
    "seedKey": "seed-entries#17",
    "date": "2026-09-10",
    "kind": "tip",
    "base": "0.00",
    "tip": "4.93",
    "wifeAlong": false,
    "tripNumber": null,
    "orders": null,
    "completedTime": null,
    "orderNumber": "200015141977277",
    "deliveredDate": "2026-09-09",
    "notes": ""
  },
  {
    "seedKey": "seed-entries#18",
    "date": "2026-09-10",
    "kind": "tip",
    "base": "0.00",
    "tip": "2.00",
    "wifeAlong": false,
    "tripNumber": null,
    "orders": null,
    "completedTime": null,
    "orderNumber": "200015144602007",
    "deliveredDate": "2026-09-09",
    "notes": ""
  },
  {
    "seedKey": "seed-entries#19",
    "date": "2026-09-10",
    "kind": "tip",
    "base": "0.00",
    "tip": "15.00",
    "wifeAlong": false,
    "tripNumber": null,
    "orders": null,
    "completedTime": null,
    "orderNumber": "200015271696791",
    "deliveredDate": "2026-09-09",
    "notes": ""
  },
  {
    "seedKey": "seed-entries#20",
    "date": "2026-09-10",
    "kind": "tip",
    "base": "0.00",
    "tip": "5.00",
    "wifeAlong": false,
    "tripNumber": null,
    "orders": null,
    "completedTime": null,
    "orderNumber": "200015159772077",
    "deliveredDate": "2026-09-09",
    "notes": ""
  },
  {
    "seedKey": "seed-entries#21",
    "date": "2026-09-11",
    "kind": "trip",
    "base": "10.00",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "5534",
    "orders": 1,
    "completedTime": "10:06 AM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#22",
    "date": "2026-09-11",
    "kind": "trip",
    "base": "27.07",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "7946",
    "orders": 3,
    "completedTime": "11:25 AM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#23",
    "date": "2026-09-11",
    "kind": "trip",
    "base": "24.50",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "0435",
    "orders": 2,
    "completedTime": "1:25 PM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#24",
    "date": "2026-09-11",
    "kind": "trip",
    "base": "21.00",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "3518",
    "orders": 2,
    "completedTime": "5:21 PM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#25",
    "date": "2026-09-11",
    "kind": "trip",
    "base": "54.37",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "2926",
    "orders": 1,
    "completedTime": "7:42 PM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#26",
    "date": "2026-09-11",
    "kind": "tip",
    "base": "0.00",
    "tip": "6.44",
    "wifeAlong": false,
    "tripNumber": null,
    "orders": null,
    "completedTime": null,
    "orderNumber": "200015179655152",
    "deliveredDate": "2026-09-10",
    "notes": ""
  },
  {
    "seedKey": "seed-entries#27",
    "date": "2026-09-12",
    "kind": "trip",
    "base": "17.28",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "7081",
    "orders": 1,
    "completedTime": "1:16 PM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#28",
    "date": "2026-09-12",
    "kind": "trip",
    "base": "21.57",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "9007",
    "orders": 3,
    "completedTime": "2:29 PM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": "Cancelled at 2:29 PM, still paid"
  },
  {
    "seedKey": "seed-entries#29",
    "date": "2026-09-12",
    "kind": "tip",
    "base": "0.00",
    "tip": "2.82",
    "wifeAlong": false,
    "tripNumber": null,
    "orders": null,
    "completedTime": null,
    "orderNumber": "200015159773449",
    "deliveredDate": "2026-09-11",
    "notes": ""
  },
  {
    "seedKey": "seed-entries#30",
    "date": "2026-09-12",
    "kind": "tip",
    "base": "0.00",
    "tip": "5.00",
    "wifeAlong": false,
    "tripNumber": null,
    "orders": null,
    "completedTime": null,
    "orderNumber": "200015149322559",
    "deliveredDate": "2026-09-11",
    "notes": ""
  },
  {
    "seedKey": "seed-entries#31",
    "date": "2026-09-12",
    "kind": "tip",
    "base": "0.00",
    "tip": "5.10",
    "wifeAlong": false,
    "tripNumber": null,
    "orders": null,
    "completedTime": null,
    "orderNumber": "200015405565265",
    "deliveredDate": "2026-09-11",
    "notes": ""
  },
  {
    "seedKey": "seed-entries#32",
    "date": "2026-09-12",
    "kind": "trip",
    "base": "43.27",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "2816",
    "orders": 1,
    "completedTime": "6:33 PM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#33",
    "date": "2026-09-12",
    "kind": "trip",
    "base": "23.42",
    "tip": "0.00",
    "wifeAlong": false,
    "tripNumber": "0091",
    "orders": 1,
    "completedTime": "7:23 PM",
    "orderNumber": null,
    "deliveredDate": null,
    "notes": ""
  },
  {
    "seedKey": "seed-entries#34",
    "date": "2026-09-12",
    "kind": "tip",
    "base": "0.00",
    "tip": "2.00",
    "wifeAlong": false,
    "tripNumber": null,
    "orders": null,
    "completedTime": null,
    "orderNumber": "200015117122703",
    "deliveredDate": "2026-09-11",
    "notes": ""
  }
];

export const SEED_LEDGER: SeedLedgerRow[] = [
  {
    "seedKey": "seed-wife-payments#1",
    "date": "2026-09-11",
    "kind": "paid",
    "amount": "41.00",
    "notes": "Earned before 9/12, orders unknown"
  },
  {
    "seedKey": "seed-wife-payments#2",
    "date": "2026-09-11",
    "kind": "paid",
    "amount": "25.00",
    "notes": "Earned before 9/12, orders unknown"
  },
  {
    "seedKey": "seed-wife-payments#3",
    "date": "2026-09-11",
    "kind": "paid",
    "amount": "20.00",
    "notes": "Earned before 9/12, orders unknown"
  },
  {
    "seedKey": "seed-wife-payments#4",
    "date": "2026-09-11",
    "kind": "paid",
    "amount": "21.00",
    "notes": "Earned before 9/12, orders unknown"
  },
  {
    "seedKey": "seed-wife-payments#5",
    "date": "2026-09-11",
    "kind": "paid",
    "amount": "38.00",
    "notes": "Earned before 9/12, orders unknown"
  }
];
