/**
 * Bakes the seed CSVs into src/lib/seed-data.ts so the app can load your
 * history without reading files at request time (nothing to bundle, nothing
 * to trace on a serverless deploy).
 *
 * Run after editing data/*.csv:
 *   npm run db:seed:gen
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { buildSeedRows } from "./seed-rows";

const { entryRows, ledgerRows } = buildSeedRows();

const out = `// GENERATED by scripts/gen-seed-data.ts — do not edit by hand.
// Source: data/seed-entries.csv, data/seed-wife-payments.csv
// Regenerate with: npm run db:seed:gen
import type { Kind, LedgerKind } from "@/db/schema";

export type SeedEntry = {
  seedKey: string;
  date: string;
  kind: Kind;
  base: string;
  tip: string;
  wifeAlong: boolean;
  tripNumber: string | null;
  orders: number | null;
  completedTime: string | null;
  orderNumber: string | null;
  deliveredDate: string | null;
  notes: string;
};

export type SeedLedgerRow = {
  seedKey: string;
  date: string;
  kind: LedgerKind;
  amount: string;
  notes: string;
};

export const SEED_ENTRIES: SeedEntry[] = ${JSON.stringify(entryRows, null, 2)};

export const SEED_LEDGER: SeedLedgerRow[] = ${JSON.stringify(ledgerRows, null, 2)};
`;

writeFileSync(resolve(process.cwd(), "src/lib/seed-data.ts"), out);
console.log(
  `Wrote src/lib/seed-data.ts — ${entryRows.length} entries, ${ledgerRows.length} ledger rows.`,
);
